### ISSUE TITLE
Put samples into a nonstandard folder or don't include them in the release bundle

### ISSUE THREAD

**Issue by voor** [vmware-labs/service-bindings#163]
I was consuming the latest release bundle and it still has the `samples` folder, this can be innocuous on a cluster that already has knative serving installed, but thankfully it errored out since I don't have all the necessary prerequisite CRDs.

```
.
├── LICENSE
├── NOTICE
├── samples
│   ├── controlled-resource
│   │   ├── application.yaml
│   │   ├── README.md
│   │   ├── service-binding.yaml
│   │   └── service.yaml
│   ├── multi-binding
│   │   ├── application.yaml
│   │   ├── README.md
│   │   ├── service-binding.yaml
│   │   └── service.yaml
│   ├── overridden-type-provider
│   │   ├── application.yaml
│   │   ├── README.md
│   │   ├── service-binding.yaml
│   │   └── service.yaml
│   ├── provisioned-service
│   │   ├── application.yaml
│   │   ├── README.md
│   │   ├── service-binding.yaml
│   │   └── service.yaml
│   └── spring-petclinic
│       ├── application.yaml
│       ├── README.md
│       ├── service-binding.yaml
│       └── service.yaml
├── service-bindings.yaml
└── VERSION
```

Suggest either moving `service-bindings.yaml` into a `config` folder (this is what a lot of other packages are doing), or just delete the sample folder entirely.

**Comment by scothis** [comment]
I'll move `service-bindings.yaml` into a `config` directory.  Having samples versioned with the release is helpful.

I assume this came up because `kapp` applies config recursively by default?

Is there a list of bundle conventions/best practices published somewhere?
