### ISSUE TITLE
Cluster Role does not have access to Jobs

### ISSUE THREAD

**Issue by rashedkvm** [vmware-labs/service-bindings#207]
**Bug description**
TAP Service Binding package the service-binding-apps Cluster Role does not have access to Jobs (just Deployment, DS, and STS)

**Expected behavior**
`service-bindings-app` cluster role should include `job`
**Steps to reproduce the bug**

**Version (Tanzu Application Platform verision, K8s version) ** 
TAP 1.0.0 (service bindings)
**Environment where the bug was observed (cloud, OS, etc)**

**Relevant Debug Output (Logs, etc)**
https://github.com/vmware-labs/service-bindings/blob/main/samples/overridden-type-provider/workload.yaml#L6

**Comment by scothis** [comment]
Jobs are supported https://github.com/vmware-labs/service-bindings/blob/b4584a8feb40374bfc335622626807c828606b41/config/200-clusterrole.yaml#L74-L76

I also verified the sample works as expected against TAP 1.0
