### ISSUE TITLE
Support CRD v1beta1 APIs while major k8s distros continue to support them

### ISSUE THREAD

**Issue by ron1** [vmware-labs/service-bindings#45]
Major k8s vendors continue to support pre-1.16 k8s versions which include the CRD v1beta APIs. Consider waiting to move to the CRD v1 APIs until pre-1.16 k8s versions are no longer supported by major vendors. See https://github.com/vmware-labs/service-bindings/pull/40.

**Comment by scothis** [comment]
Unfortunately, the underlaying knative libraries we use have k8s 1.16 as a minimum supported version.

**Comment by scothis** [comment]
@ron1 is k8s 1.16 a blocker for you?

**Comment by ron1** [comment]
@scothis Unfortunately, yes.

**Comment by scothis** [comment]
@ron1 can you provide a little more info about your environment? K8s 1.15 is no longer [supported upstream](https://kubernetes.io/docs/setup/release/version-skew-policy/)

**Comment by ron1** [comment]
@scothis Unfortunately, I will be stuck on OpenShift 3.11 (based on patched k8s 1.11) for a while. Red Hat plans to continue full support for OCP 3.11 through June 2021. Since OCP 3.11 has a large installed base and no in-place upgrade path exists to OCP 4, most operator/controller providers seem to be extending their support for the platform despite its age.

Also, it seems that the upgrade from k8s 1.15 to 1.16+ is more painful than most due primarily to the introduction of CRD API v1. As a result, k8s providers may decide to extend their support for k8s 1.15 for longer than normal. This might be another reason to consider implementing a solution for this issue.

**Comment by mattmoor** [comment]
Depending on the functionality it is pulling in from knative.dev/pkg, it is possible that you can override the version via an [env variable](https://github.com/knative/pkg/blob/b5411f2221aa3fdf85e23a53f412aa9bc1730c5c/version/version.go#L31), but a lot has landed since 1.11 (e.g. CRD v1, webhook v1, ...)

I wonder how far off we are, but I'd guess with the CRD v1 migration we changed reconcilers which makes it more than a config change... 😞 

cc @dprotaso (bumped some of the api groups we use)
cc @pmorie (since it touches Openshift / Bindings)

**Comment by scothis** [comment]
> Depending on the functionality it is pulling in from knative.dev/pkg, it is possible that you can override the version via an env variable, but a lot has landed since 1.11 (e.g. CRD v1, webhook v1, ...)

I tired, knative.dev/pkg uses webhook v1 internally, so the controller blows up quickly. There may be more issues after that one. If knative.dev/pkg downgraded to v1beta1 it may work, I doubt it actually needs the v1 version of those resources, other than to future proof. The v1beta1 apis is scheduled for removal with k8s 1.22.

**Comment by scothis** [comment]
knative.dev/pkg 0.17 (#52) adds a dependency on the coordination api which went beta in k8s 1.12. k8s 1.11 is just too old for us to practically support.

Service Bindings is a new project, and while it's unfortunately that you can't use it in an existing cluster, the project is currently alpha and shouldn't be used in production environments right now.
