### ISSUE TITLE
Invitation/Proposal to collaborate on a single implementation

### ISSUE THREAD

**Issue by sbose78** [vmware-labs/service-bindings#59]
Hi @scothis @nebhale , 

I’m Shoubhik, a maintainer of [redhat-developer/service-binding-operator](https://github.com/redhat-developer/service-binding-operator) . The project, kicked-off in June 2019 has evolved significantly since then based on the feedback we've received from our users.

Recently, it’s been proposed that we support [k8s-service-bindings/spec](https://github.com/vmware-labs/service-bindings) in our project alongside our current implementation. The new implementation as far as I understand would be along the lines of [vmware-labs/service-bindings](https://github.com/vmware-labs/service-bindings) based on [k8s-service-bindings/spec](https://github.com/k8s-service-bindings/spec) .

Therefore, I was wondering if you would be interested in collaborating on a single implementation of Service Binding, instead of VMware and Red Hat working on their own ? 

From a logistics standpoint, among other things, that would imply 
* A code repository for a Service Binding implementation for Kubernetes, in a neutral Github org
* A governance where the founding contributors have an equal number of seats ( Red Hat: N, VMware: N , IBM: N, and Others who would want to join? ). 
* This could be expanded to follow a standard open source governance model with a plan to donate it to a foundation.

Details would need to be worked out for sure, but I wanted to check if this would be something you would want to consider. Let me know!

Best wishes,
Shoubhik

 cc @arthurdm @pedjak

**Comment by scothis** [comment]
Thanks for opening this issue @sbose78 

Since our last interlock call, I floated this idea amongst our leadership. It received a warm reception with a couple caveats:

1. governance needs to be sorted out (no surprise here)
2. use of the "k8s" mark needs to be clarified since this is not part of the Kubernetes project

Both of these concerns could be addressed by the Service Binding effort folding under the Kubernetes SIGs. This is a larger discussion that we should be upstream.

There were a handful of other comments about the spec that I can open issues for.

In the mean time, are their contributions you're looking to make to the existing implementation?

**Comment by baijum** [comment]
Which SIG would be the right place to discuss the spec and implementation? Is it [sig-apps](https://github.com/kubernetes/community/tree/master/sig-apps)?

**Comment by sbose78** [comment]
@scothis 

Thank you! 

Yeah, the use of "k8s" would be tricky and yes, a SIG conversation probably will solve a lot of the aforementioned issues. 

Additionally, we could engage with the open source program offices in our respective orgs to figure out the appropriate name/home for the project.

> Yes, if there's a SIG we can start/be a part of, that does solve a lot of these.

I do want to figure out a path to common implementation that would enable us to preserve the good work that our respective teams have done in [1], [2], [3], to make things simpler for the wider community to adopt.

[1] https://github.com/vmware-labs/service-bindings
[2] https://github.com/redhat-developer/service-binding-operator
[3] https://github.com/k8s-service-bindings/spec

**Comment by arthurdm** [comment]
hey guys - great discussion here.  

Would the goal be to contribute to a common reference implementation of the spec (using components from both this VMWare impl and Red Hat's impl), living in the same org as the spec?

I think it's a great collaboration, as they each bring unique value-add.

**Comment by scothis** [comment]
@sbose78 @baijum @arthurdm given the direction of https://github.com/k8s-service-bindings/spec/issues/138, is it worth rekindling this discussion?

**Comment by sbose78** [comment]
Definitely!

**Comment by scothis** [comment]
We're going to do this! Tracking the work upstream

**Comment by sbose78** [comment]
💯
