### ISSUE TITLE
Infinite reconcile loop when injecting multiple service bindings into a single application

### ISSUE THREAD

**Issue by arturdzm** [vmware-labs/service-bindings#66]
When creating 2 separate ServiceBinding resources with different service selectors but pointing to same application (regular Deployment) the deployment gets into infinite reconcile loop.

Each version of deployment has only info from one of ServiceBinding CRs and it keeps switching
It seems that mounted volumes order keeps changing as well as env keeps being added and removed and each version of Deployment

**Comment by scothis** [comment]
I think what's happening is that when we apply the binding, we first remove the existing binding to restore the resource to a clean state, and then add the binding back in. The cleanup is too aggressive in removing state that isn't specifically for the binding being reconciled. That or there's an upstream bug in knative/pkg.

**Comment by arturdzm** [comment]
From what I looked at, I think the psbinding package assumes 1 binding to 1 PodSpec mapping.
It works with multiple CRDs like GithubBinding TwitterBinding, etc but not when there is more the one of same type

**Comment by scothis** [comment]
@arturdzm can you take #75 for a spin to see if it helps your use case? If it does I'll cleanup the TODOs and get it merged.

**Comment by scothis** [comment]
With #75 I no longer see this behavior. Please reopen with a test case if you still see service bindings clashing

**Comment by scothis** [comment]
There's still an upstream issue, tracking in #78

**Comment by arturdzm** [comment]
Thanks, works for me as well
