### ISSUE TITLE
ServiceBindingProjection not created

### ISSUE THREAD

**Issue by johnpoth** [vmware-labs/service-bindings#79]
Hi guys, great project!

I am trying to create a custom projection as so:

```
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  annotations:
    projection.service.binding/type: Custom
  name: custom-projection
  namespace: service-binding
spec:
  application:
    apiVersion: v1
    kind: Deployment
    name: sample
  service:
    apiVersion: postgresql.baiju.dev/v1alpha1
    kind: Database
    name: db-demo
```
as described in the samples, using my own app and database. However no ServiceBindingProjection resource is created. The status of the ServiceBinding is updated:

```status:
  conditions:
  - lastTransitionTime: "2020-10-08T18:02:59Z"
    status: Unknown
    type: ProjectionReady
  - lastTransitionTime: "2020-10-08T18:02:59Z"
    message: unsuccessfully observed a new generation
    reason: NewObservedGenFailure
    status: Unknown
    type: Ready
  - lastTransitionTime: "2020-10-08T18:02:59Z"
    status: Unknown
    type: ServiceAvailable
  observedGeneration: 1
```

Manager pod [logs](https://gist.githubusercontent.com/johnpoth/01bc5343920f66320a48f9fc49b873da/raw/5eb18ed8144e61138faa5c13d5b087502c17fb60/logs.txt)

Event triggered by manager pod:

```
apiVersion: v1
count: 2
eventTime: null
firstTimestamp: "2020-10-08T18:02:59Z"
involvedObject:
  apiVersion: service.binding/v1alpha2
  kind: ServiceBinding
  name: custom-projection
  namespace: service-binding
  resourceVersion: "2742820"
  uid: 541b7bcd-8227-413c-b7ec-f975e93e33b1
kind: Event
lastTimestamp: "2020-10-08T18:02:59Z"
message: 'ServiceBinding reconciled: "service-binding/custom-projection"'
metadata:
  creationTimestamp: "2020-10-08T18:02:59Z"
  name: custom-projection.163c16627b7b87a9
  namespace: service-binding
  resourceVersion: "2742822"
  selfLink: /api/v1/namespaces/service-binding/events/custom-projection.163c16627b7b87a9
  uid: 7b68852a-1849-4dff-9414-2fa45db3c2ea
reason: Reconciled
reportingComponent: ""
reportingInstance: ""
source:
  component: servicebinding-controller
type: Normal
```

Thanks!

**Comment by scothis** [comment]
Welcome @johnpoth 

The error message should be better, but it looks like the service isn't exposing the binding secret. Can you show the content of `postgresql.baiju.dev/v1alpha1:Database db-demo`? In particular, it needs to have a value at `.status.binding.name` that is the name of a secret in the same namespace.

If you use the [custom projection sample](https://github.com/vmware-labs/service-bindings/tree/main/samples/custom-projection) directly it should work.

**Comment by johnpoth** [comment]
Thanks @scothis ! Indeed `postgresql.baiju.dev/v1alpha1:Database db-demo` didn't have a `.status.binding.name` value set.

I've tried the custom projection sample directly but still no `ServiceBindingProjection` was created. 

Here's the ServiceBinding with its status updated:

```
apiVersion: service.binding/v1alpha2
kind: ServiceBinding
metadata:
  annotations:
    projection.service.binding/type: Custom
  creationTimestamp: "2020-10-13T07:21:39Z"
  generation: 1
  name: custom
  namespace: service-binding
  resourceVersion: "3305200"
  selfLink: /apis/service.binding/v1alpha2/namespaces/service-binding/servicebindings/custom
  uid: 0eaadbd6-5aaa-425e-9c21-c72d424d043a
spec:
  application:
    apiVersion: v1
    kind: ConfigMap
    name: custom
  name: custom
  service:
    apiVersion: v1
    kind: Secret
    name: custom
status:
  conditions:
  - lastTransitionTime: "2020-10-13T07:21:39Z"
    status: Unknown
    type: ProjectionReady
  - lastTransitionTime: "2020-10-13T07:21:39Z"
    message: unsuccessfully observed a new generation
    reason: NewObservedGenFailure
    status: Unknown
    type: Ready
  - lastTransitionTime: "2020-10-13T07:21:39Z"
    status: Unknown
    type: ServiceAvailable
  observedGeneration: 1
```

and [logs](https://gist.github.com/johnpoth/0b84f443f28ba998b1af118aa184f8f1) from the manager pod.

**Comment by scothis** [comment]
The samples on the main branch currently require a custom install from the main branch. Direct binding from Secrets is on main but not yet in a release. Hope to get a release out this week. The other option is to use the samples from the release tag you installed.

**Comment by scothis** [comment]
[v0.3.0](https://github.com/vmware-labs/service-bindings/releases/tag/v0.3.0) is hot off the presses and will work for you.

**Comment by scothis** [comment]
Closing, but please reopen if you continue to have trouble.
